apply plugin: 'com.android.library'


android {
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
    }


}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    api files('libs/core-3.3.3.jar')
    compileOnly "com.android.support:appcompat-v7:28.0.0"
    compileOnly "com.android.support:design:28.0.0"
    compileOnly "com.android.support:support-v4:28.0.0"
    compileOnly "com.android.support:support-vector-drawable:28.0.0"

}
